file(REMOVE_RECURSE "${SE_WORK}")
file(MAKE_DIRECTORY "${SE_WORK}")
execute_process(
  COMMAND "${SE_EXE}" web build "${SE_ROOT}/examples/component-web.se" "${SE_WORK}/dist"
  RESULT_VARIABLE result
  OUTPUT_VARIABLE output
  ERROR_VARIABLE error
)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "SE component web build failed:\n${output}\n${error}")
endif()
foreach(name index.html style.css app.js app.ts)
  if(NOT EXISTS "${SE_WORK}/dist/${name}")
    message(FATAL_ERROR "Missing generated ${name}")
  endif()
endforeach()
file(READ "${SE_WORK}/dist/index.html" html)
file(READ "${SE_WORK}/dist/style.css" css)
file(READ "${SE_WORK}/dist/app.js" js)
string(REGEX MATCHALL "data-se-instance=\"se-Button-[0-9]+\"" button_instances "${html}")
list(LENGTH button_instances button_count)
if(NOT button_count EQUAL 3)
  message(FATAL_ERROR "Expected three independent Button instances, got ${button_count}\n${html}")
endif()
if(NOT html MATCHES ">Save</button>" OR NOT html MATCHES ">Cancel</button>" OR NOT html MATCHES ">Next</button>")
  message(FATAL_ERROR "Generated HTML is missing Button text\n${html}")
endif()
if(NOT css MATCHES "\\.se-Button" OR NOT css MATCHES "padding: 12px" OR NOT css MATCHES "border-radius: 8px")
  message(FATAL_ERROR "Generated component CSS is missing scoped Button styles\n${css}")
endif()
if(NOT js MATCHES "addEventListener\\(\"click\"" OR NOT js MATCHES "Save" OR NOT js MATCHES "Cancel" OR NOT js MATCHES "Next")
  message(FATAL_ERROR "Generated JavaScript is missing instance event bindings\n${js}")
endif()
message(STATUS "SE component web build passed")
