file(MAKE_DIRECTORY "${S_WORK}")
function(check_parity name source)
  set(run_out "${S_WORK}/${name}.run.txt")
  set(native_out "${S_WORK}/${name}.native.txt")
  execute_process(COMMAND "${S_EXE}" run "${source}" RESULT_VARIABLE run_code OUTPUT_FILE "${run_out}" ERROR_VARIABLE run_err)
  if(NOT run_code EQUAL 0) message(FATAL_ERROR "se run failed for ${name}: ${run_err}") endif()
  execute_process(COMMAND "${S_EXE}" build "${source}" RESULT_VARIABLE build_code OUTPUT_VARIABLE build_out ERROR_VARIABLE build_err)
  if(NOT build_code EQUAL 0) message(FATAL_ERROR "se build failed for ${name}: ${build_out}\n${build_err}") endif()
  get_filename_component(exe "${source}" NAME_WE)
  get_filename_component(dir "${source}" DIRECTORY)
  if(WIN32) set(exe "${exe}.exe") endif()
  execute_process(COMMAND "${dir}/${exe}" RESULT_VARIABLE native_code OUTPUT_FILE "${native_out}" ERROR_VARIABLE native_err)
  if(NOT native_code EQUAL 0) message(FATAL_ERROR "native executable failed for ${name}: ${native_err}") endif()
  file(READ "${run_out}" a)
  file(READ "${native_out}" b)
  if(NOT a STREQUAL b) message(FATAL_ERROR "Interpreter/native mismatch for ${name}.\nrun: ${a}\nnative: ${b}") endif()
endfunction()
file(COPY "${S_ROOT}/examples/type.se" DESTINATION "${S_WORK}")
file(COPY "${S_ROOT}/examples/collections.se" DESTINATION "${S_WORK}")
file(COPY "${S_ROOT}/examples/modules" DESTINATION "${S_WORK}")
check_parity(type "${S_WORK}/type.se")
check_parity(collections "${S_WORK}/collections.se")
check_parity(modules "${S_WORK}/modules/main.se")
set(ENV{SE_NATIVE_PATH} "${S_NATIVE_DIR}")
file(COPY "${S_ROOT}/examples/native/main.se" DESTINATION "${S_WORK}")
check_parity(native "${S_WORK}/main.se")
