#include "s/web_compiler.hpp"
#include "s/error.hpp"

#include <iomanip>
#include <memory>
#include <sstream>
#include <string>
#include <unordered_set>
#include <utility>

namespace s {
namespace {

std::string quote_js(const std::string& value){
  std::ostringstream out; out<<'"';
  for(unsigned char c:value){
    switch(c){
      case '\\':out<<"\\\\";break; case '"':out<<"\\\"";break;
      case '\n':out<<"\\n";break; case '\r':out<<"\\r";break; case '\t':out<<"\\t";break;
      default: if(c<0x20)out<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<static_cast<int>(c)<<std::dec;else out<<static_cast<char>(c);
    }
  }
  out<<'"'; return out.str();
}

std::string html_escape(const std::string& value){
  std::string out;out.reserve(value.size());
  for(char c:value){
    switch(c){case '&':out+="&amp;";break;case '<':out+="&lt;";break;case '>':out+="&gt;";break;case '"':out+="&quot;";break;default:out+=c;}
  }
  return out;
}

std::string literal_text(const ast::ExprPtr& expr,SourcePos p,const std::string& what){
  auto literal=std::dynamic_pointer_cast<ast::Literal>(expr);
  if(!literal)throw Error(p,what+" must be literal Text in an SE web build.");
  if(auto value=std::get_if<std::string>(&literal->value))return *value;
  throw Error(p,what+" must be Text.");
}

bool ui_call(const ast::StmtPtr& stmt,const std::string& name,std::shared_ptr<ast::Call>& call){
  auto expression=std::dynamic_pointer_cast<ast::ExprStmt>(stmt); if(!expression)return false;
  call=std::dynamic_pointer_cast<ast::Call>(expression->value); if(!call)return false;
  auto member=std::dynamic_pointer_cast<ast::Member>(call->callee); if(!member||member->name!=name)return false;
  auto object=std::dynamic_pointer_cast<ast::Variable>(member->value); return object&&object->name=="ui";
}

class JsEmitter {
public:
  std::string emit(const ast::Program& program){
    out_<<runtime_prelude();
    scopes_.push_back({});
    for(const auto& stmt:program.statements) statement(stmt,0);
    scopes_.pop_back();
    return out_.str();
  }
private:
  std::ostringstream out_;
  std::vector<std::unordered_set<std::string>> scopes_;
  int temp_=0;

  static std::string runtime_prelude(){
    return R"JS(// Generated by SE web build. Edit the .se source, not this file.
const __seRange=(a,b)=>{const out=[];for(let i=a;i<=b;i+=1)out.push(i);return out;};
const __seIn=(value,container)=>container instanceof Set?container.has(value):Array.isArray(container)?container.includes(value):typeof container==='string'?container.includes(value):container&&typeof container==='object'?Object.prototype.hasOwnProperty.call(container,value):false;
const __seAsk=(question)=>globalThis.prompt?globalThis.prompt(String(question))??'':'';
const ui={
  el(tag,text='',attrs={}){const node=document.createElement(String(tag));if(text!==''&&text!==null&&text!==undefined)node.textContent=String(text);for(const [name,value] of Object.entries(attrs||{}))node.setAttribute(String(name),String(value));return node;},
  add(parent,...children){parent.append(...children);return parent;},
  mount(node,target='#app'){const host=typeof target==='string'?document.querySelector(target):target;if(!host)throw new Error(`SE ui.mount target not found: ${target}`);host.replaceChildren(node);return node;},
  find(selector){return document.querySelector(String(selector));},
  all(selector){return [...document.querySelectorAll(String(selector))];},
  attr(node,name,value){node.setAttribute(String(name),String(value));return node;},
  attrs(node,values){for(const [name,value] of Object.entries(values||{}))node.setAttribute(String(name),String(value));return node;},
  text(node,value){node.textContent=String(value);return node;},
  html(node,value){node.innerHTML=String(value);return node;},
  value(node){return node&&'value' in node?node.value:'';},
  set_value(node,value){if(node&&'value' in node)node.value=String(value);return node;},
  class(node,name,on=true){node.classList.toggle(String(name),Boolean(on));return node;},
  on(node,event,handler){node.addEventListener(String(event),eventValue=>handler(eventValue));return node;},
  style(selector,values){const rule=Object.entries(values).map(([k,v])=>`${k}:${v}`).join(';');const style=document.createElement('style');style.textContent=`${selector}{${rule}}`;document.head.append(style);return style;},
  fetch:async(url,options={})=>{const response=await fetch(String(url),options);if(!response.ok)throw new Error(`HTTP ${response.status}`);const type=response.headers.get('content-type')||'';return type.includes('application/json')?response.json():response.text();}
};

)JS";
  }

  void indent(int depth){for(int i=0;i<depth;++i)out_<<"  ";}
  bool declared(const std::string& name) const{for(auto i=scopes_.rbegin();i!=scopes_.rend();++i)if(i->contains(name))return true;return false;}
  void declare_here(const std::string& name){scopes_.back().insert(name);}

  std::string expression(const ast::ExprPtr& e){
    if(auto x=std::dynamic_pointer_cast<ast::Literal>(e)){
      if(auto v=std::get_if<std::int64_t>(&x->value))return std::to_string(*v);
      if(auto v=std::get_if<double>(&x->value)){std::ostringstream s;s<<std::setprecision(17)<<*v;return s.str();}
      if(auto v=std::get_if<std::string>(&x->value))return quote_js(*v);
      return std::get<bool>(x->value)?"true":"false";
    }
    if(auto x=std::dynamic_pointer_cast<ast::Duration>(e))return std::to_string(x->milliseconds);
    if(auto x=std::dynamic_pointer_cast<ast::Variable>(e))return x->name;
    if(auto x=std::dynamic_pointer_cast<ast::List>(e)){std::string r="[";for(std::size_t i=0;i<x->items.size();++i){if(i)r+=",";r+=expression(x->items[i]);}return r+"]";}
    if(auto x=std::dynamic_pointer_cast<ast::Set>(e)){std::string r="new Set([";for(std::size_t i=0;i<x->items.size();++i){if(i)r+=",";r+=expression(x->items[i]);}return r+"])";}
    if(auto x=std::dynamic_pointer_cast<ast::Map>(e)){std::string r="({";for(std::size_t i=0;i<x->items.size();++i){if(i)r+=",";r+="["+expression(x->items[i].first)+"]:"+expression(x->items[i].second);}return r+"})";}
    if(auto x=std::dynamic_pointer_cast<ast::Index>(e))return expression(x->value)+"["+expression(x->index)+"]";
    if(auto x=std::dynamic_pointer_cast<ast::Member>(e))return expression(x->value)+"."+x->name;
    if(auto x=std::dynamic_pointer_cast<ast::Ask>(e))return "__seAsk("+expression(x->question)+")";
    if(auto x=std::dynamic_pointer_cast<ast::Range>(e))return "__seRange("+expression(x->start)+","+expression(x->end)+")";
    if(auto x=std::dynamic_pointer_cast<ast::TryExpr>(e))return expression(x->value);
    if(auto x=std::dynamic_pointer_cast<ast::Unary>(e)){
      auto op=x->op==TokenKind::Not?"!":"-";return std::string(op)+"("+expression(x->value)+")";
    }
    if(auto x=std::dynamic_pointer_cast<ast::Binary>(e)){
      if(x->op==TokenKind::In)return "__seIn("+expression(x->left)+","+expression(x->right)+")";
      std::string op;
      switch(x->op){
        case TokenKind::Plus:op="+";break;case TokenKind::Minus:op="-";break;case TokenKind::Star:op="*";break;
        case TokenKind::Slash:op="/";break;case TokenKind::Percent:op="%";break;case TokenKind::Power:op="**";break;
        case TokenKind::EqualEqual:op="===";break;case TokenKind::BangEqual:op="!==";break;case TokenKind::Greater:op=">";break;
        case TokenKind::Less:op="<";break;case TokenKind::GreaterEqual:op=">=";break;case TokenKind::LessEqual:op="<=";break;
        case TokenKind::And:op="&&";break;case TokenKind::Or:op="||";break;default:throw Error(x->pos,"This SE operator is not supported by web build yet.");
      }
      return "("+expression(x->left)+" "+op+" "+expression(x->right)+")";
    }
    if(auto x=std::dynamic_pointer_cast<ast::Call>(e)){
      std::string r=expression(x->callee)+"(";for(std::size_t i=0;i<x->args.size();++i){if(i)r+=",";r+=expression(x->args[i]);}return r+")";
    }
    throw Error(e->pos,"This SE expression is not supported by web build yet.");
  }

  void block(const ast::Block& statements,int depth){scopes_.push_back({});for(const auto& stmt:statements)statement(stmt,depth);scopes_.pop_back();}

  void statement(const ast::StmtPtr& s,int depth){
    if(std::dynamic_pointer_cast<ast::Use>(s))return;
    if(auto x=std::dynamic_pointer_cast<ast::Say>(s)){indent(depth);out_<<"console.log("<<expression(x->value)<<");\n";return;}
    if(auto x=std::dynamic_pointer_cast<ast::ExprStmt>(s)){indent(depth);out_<<expression(x->value)<<";\n";return;}
    if(auto x=std::dynamic_pointer_cast<ast::Assign>(s)){
      if(auto name=std::dynamic_pointer_cast<ast::Variable>(x->target)){
        indent(depth);
        bool first=!declared(name->name);
        if(first){out_<<"let ";declare_here(name->name);}
        if(!x->init.empty()){
          auto type=std::dynamic_pointer_cast<ast::Variable>(x->value);if(!type)throw Error(x->pos,"SE web object initialization needs a user type name.");
          out_<<name->name<<" = new "<<type->name<<"({";
          bool comma=false;for(const auto& item:x->init){auto a=std::dynamic_pointer_cast<ast::Assign>(item);auto f=a?std::dynamic_pointer_cast<ast::Variable>(a->target):nullptr;if(!a||!f)throw Error(item->pos,"SE web object initialization only supports field assignments.");if(comma)out_<<',';comma=true;out_<<quote_js(f->name)<<':'<<expression(a->value);}out_<<"});\n";
        }else out_<<name->name<<" = "<<expression(x->value)<<";\n";
        return;
      }
      indent(depth);out_<<expression(x->target)<<" = "<<expression(x->value)<<";\n";return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::If>(s)){
      indent(depth);out_<<"if("<<expression(x->condition)<<"){\n";block(x->then_block,depth+1);indent(depth);out_<<"}";
      if(!x->else_block.empty()){out_<<"else{\n";block(x->else_block,depth+1);indent(depth);out_<<"}";}out_<<"\n";return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::Repeat>(s)){
      auto n="__seRepeat"+std::to_string(temp_++);indent(depth);out_<<"for(let "<<n<<"=0;"<<n<<"<"<<expression(x->count)<<";"<<n<<"+=1){\n";block(x->body,depth+1);indent(depth);out_<<"}\n";return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::For>(s)){
      indent(depth);
      if(x->names.size()==1)out_<<"for(const "<<x->names[0]<<" of "<<expression(x->values)<<"){\n";
      else out_<<"for(const ["<<x->names[0]<<","<<x->names[1]<<"] of Object.entries("<<expression(x->values)<<")){\n";
      scopes_.push_back({});for(const auto& name:x->names)declare_here(name);for(const auto& item:x->body)statement(item,depth+1);scopes_.pop_back();indent(depth);out_<<"}\n";return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::While>(s)){indent(depth);out_<<"while("<<expression(x->condition)<<"){\n";block(x->body,depth+1);indent(depth);out_<<"}\n";return;}
    if(auto x=std::dynamic_pointer_cast<ast::Function>(s)){
      indent(depth);out_<<"function "<<x->name<<"(";for(std::size_t i=0;i<x->params.size();++i){if(i)out_<<',';out_<<x->params[i];}out_<<"){\n";
      scopes_.push_back({});for(const auto& p:x->params)declare_here(p);for(const auto& item:x->body)statement(item,depth+1);scopes_.pop_back();indent(depth);out_<<"}\n";declare_here(x->name);return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::Give>(s)){indent(depth);out_<<"return "<<expression(x->value)<<";\n";return;}
    if(auto x=std::dynamic_pointer_cast<ast::Type>(s)){
      indent(depth);out_<<"class "<<x->name<<"{\n";indent(depth+1);out_<<"constructor(init={}){\n";
      for(const auto& f:x->fields){indent(depth+2);out_<<"this."<<f.name<<" = Object.prototype.hasOwnProperty.call(init,"<<quote_js(f.name)<<") ? init["<<quote_js(f.name)<<"] : ";if(f.has_default)out_<<expression(f.value);else out_<<"undefined";out_<<";\n";}
      indent(depth+1);out_<<"}\n";
      for(const auto& m:x->methods){indent(depth+1);out_<<m->name<<"(";for(std::size_t i=0;i<m->params.size();++i){if(i)out_<<',';out_<<m->params[i];}out_<<"){\n";for(const auto& item:m->body)statement(item,depth+2);indent(depth+1);out_<<"}\n";}
      indent(depth);out_<<"}\n";declare_here(x->name);return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::Try>(s)){
      indent(depth);out_<<"try{\n";block(x->body,depth+1);indent(depth);out_<<"}catch("<<x->error_name<<"){\n";scopes_.push_back({x->error_name});for(const auto& item:x->else_block)statement(item,depth+1);scopes_.pop_back();indent(depth);out_<<"}\n";return;
    }
    if(auto x=std::dynamic_pointer_cast<ast::Fail>(s)){indent(depth);out_<<"throw new Error(String("<<expression(x->value)<<"));\n";return;}
    if(auto x=std::dynamic_pointer_cast<ast::Match>(s)){
      auto name="__seMatch"+std::to_string(temp_++);indent(depth);out_<<"const "<<name<<" = "<<expression(x->value)<<";\n";
      for(std::size_t i=0;i<x->cases.size();++i){indent(depth);out_<<(i?"else if":"if")<<"("<<name<<" === "<<expression(x->cases[i].pattern)<<"){\n";block(x->cases[i].body,depth+1);indent(depth);out_<<"}";if(i+1==x->cases.size()&&x->else_block.empty())out_<<"\n";}
      if(!x->else_block.empty()){out_<<"else{\n";block(x->else_block,depth+1);indent(depth);out_<<"}\n";}return;
    }
    throw Error(s->pos,"This SE statement is not supported by web build yet.");
  }
};

std::string css_from_program(const ast::Program& program){
  std::ostringstream css;
  for(const auto& stmt:program.statements){
    std::shared_ptr<ast::Call> call;if(!ui_call(stmt,"style",call)||call->args.size()!=2)continue;
    auto selector=literal_text(call->args[0],call->pos,"ui.style selector");
    auto map=std::dynamic_pointer_cast<ast::Map>(call->args[1]);if(!map)continue;
    css<<selector<<" {\n";
    for(const auto& [key,value]:map->items){
      auto k=literal_text(key,key->pos,"CSS property");auto v=literal_text(value,value->pos,"CSS value");css<<"  "<<k<<": "<<v<<";\n";
    }
    css<<"}\n\n";
  }
  return css.str();
}

std::string title_from_program(const ast::Program& program){
  for(const auto& stmt:program.statements){std::shared_ptr<ast::Call> call;if(ui_call(stmt,"page",call)&&call->args.size()==1)return literal_text(call->args[0],call->pos,"ui.page title");}
  return "SE Web";
}

ast::Program runtime_program(const ast::Program& program){
  ast::Program out=program;out.statements.clear();
  for(const auto& stmt:program.statements){std::shared_ptr<ast::Call> call;if(ui_call(stmt,"page",call)||ui_call(stmt,"style",call))continue;out.statements.push_back(stmt);}return out;
}

} // namespace

WebBundle WebCompiler::generate(const ast::Program& program){
  auto title=title_from_program(program);auto css=css_from_program(program);auto runtime=runtime_program(program);auto js=JsEmitter{}.emit(runtime);
  std::string html="<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n  <title>"+html_escape(title)+"</title>\n  <link rel=\"stylesheet\" href=\"./style.css\">\n</head>\n<body>\n  <div id=\"app\"></div>\n  <script type=\"module\" src=\"./app.js\"></script>\n</body>\n</html>\n";
  std::string ts="// TypeScript-compatible output generated from SE.\n"+js;
  return {std::move(html),std::move(css),std::move(js),std::move(ts)};
}

} // namespace s
