#include "s/bindgen.hpp"
#include "s/error.hpp"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace s {
namespace {
struct BindingFunction {
  std::string name;
  std::string target;
  std::vector<std::string> args;
  std::string result;
  bool fallible=false;
};

std::vector<std::string> words(const std::string& line){
  std::istringstream in(line);
  std::vector<std::string> out;
  for(std::string word;in>>word;) out.push_back(word);
  return out;
}

bool identifier(const std::string& text){
  if(text.empty()||(!std::isalpha(static_cast<unsigned char>(text[0]))&&text[0]!='_')) return false;
  return std::all_of(text.begin()+1,text.end(),[](unsigned char c){return std::isalnum(c)||c=='_';});
}

std::string c_type(const std::string& type){
  if(type=="Int") return "int";
  if(type=="Num") return "double";
  if(type=="Bool") return "int";
  if(type=="Text") return "const char*";
  if(type=="Bytes") return "SBytesView";
  if(type=="None") return "void";
  throw std::runtime_error("Binding generator does not support type '"+type+"'.");
}

std::string join_args(const std::vector<std::string>& args,bool declarations){
  std::string out;
  for(std::size_t i=0;i<args.size();++i){
    if(i) out+=", ";
    if(declarations) out+=c_type(args[i])+" a"+std::to_string(i);
    else out+="a"+std::to_string(i);
  }
  if(args.empty()&&declarations) return "void";
  return out;
}

void write_file(const std::filesystem::path& path,const std::string& content){
  std::ofstream out(path,std::ios::binary|std::ios::trunc);
  if(!out) throw std::runtime_error("Could not write generated binding file '"+path.string()+"'.");
  out<<content;
  if(!out) throw std::runtime_error("Writing generated binding file failed: '"+path.string()+"'.");
}
}

BindingOutputs generate_bindings(const std::filesystem::path& definition,const std::filesystem::path& output_directory){
  std::ifstream in(definition);
  if(!in) throw std::runtime_error("Could not open binding definition '"+definition.string()+"'.");

  std::string module;
  std::string library;
  std::string header;
  std::vector<BindingFunction> functions;
  std::string line;
  int line_number=0;
  while(std::getline(in,line)){
    ++line_number;
    auto hash=line.find('#');
    if(hash!=std::string::npos) line.resize(hash);
    auto w=words(line);
    if(w.empty()) continue;
    if(w[0]=="module"){
      if(w.size()!=2||!identifier(w[1])) throw Error({line_number,1},"Binding module line must be: module name");
      module=w[1];
      continue;
    }
    if(w[0]=="library"){
      if(w.size()!=2) throw Error({line_number,1},"Binding library line must be: library name");
      library=w[1];
      continue;
    }
    if(w[0]=="header"){
      if(w.size()!=2) throw Error({line_number,1},"Binding header line must be: header file.h");
      header=w[1];
      continue;
    }
    if(w.size()<4||!identifier(w[0])||!identifier(w[1])) throw Error({line_number,1},"Binding function line must start with: name native_symbol ... -> ReturnType");
    auto arrow=std::find(w.begin()+2,w.end(),"->");
    if(arrow==w.end()||arrow+1==w.end()) throw Error({line_number,1},"Binding function needs '-> ReturnType'.");
    BindingFunction f;
    f.name=w[0];
    f.target=w[1];
    for(auto i=w.begin()+2;i!=arrow;++i){
      if(*i=="None") throw Error({line_number,1},"None cannot be a function argument.");
      (void)c_type(*i);
      f.args.push_back(*i);
    }
    f.result=*(arrow+1);
    (void)c_type(f.result);
    for(auto i=arrow+2;i!=w.end();++i){
      if(*i=="fallible") f.fallible=true;
      else throw Error({line_number,1},"Unknown binding option '"+*i+"'.");
    }
    functions.push_back(std::move(f));
  }

  if(module.empty()) throw std::runtime_error("Binding definition needs a 'module name' line.");
  if(header.empty()) throw std::runtime_error("Binding definition needs a 'header file.h' line.");
  if(library.empty()) library=module;
  if(functions.empty()) throw std::runtime_error("Binding definition has no functions.");

  std::error_code ec;
  std::filesystem::create_directories(output_directory,ec);
  if(ec) throw std::runtime_error("Could not create binding output directory '"+output_directory.string()+"'.");

  BindingOutputs paths{
    output_directory/(module+".snative"),
    output_directory/(module+"_bindings.h"),
    output_directory/(module+"_bindings.cpp")
  };

  std::string metadata="# Generated by s bind.\nlibrary "+library+"\n";
  std::string declarations="#pragma once\n#include \"s/native.h\"\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n";
  std::string source="#include \""+header+"\"\n#include \""+paths.header.filename().string()+"\"\n\n";
  for(const auto& f:functions){
    const std::string wrapper="s_"+module+"_"+f.name;
    metadata+=f.name+" "+wrapper;
    for(const auto& arg:f.args) metadata+=" "+arg;
    metadata+=" -> "+f.result;
    if(f.fallible) metadata+=" fallible";
    metadata+='\n';

    const auto result_type=c_type(f.result);
    const auto declaration_args=join_args(f.args,true);
    const auto call_args=join_args(f.args,false);
    declarations+=result_type+" "+wrapper+"("+declaration_args+");\n";
    source+="extern \"C\" "+result_type+" "+wrapper+"("+declaration_args+"){";
    if(f.result!="None") source+="return ";
    source+=f.target+"("+call_args+");";
    source+="}\n";
  }
  declarations+="#ifdef __cplusplus\n}\n#endif\n";

  write_file(paths.metadata,metadata);
  write_file(paths.header,declarations);
  write_file(paths.source,source);
  return paths;
}

} // namespace s
